# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aef4ff4c9f4fdda70b3359a2168748f5007dcf78f91aa18ad4ccf1c21c8f9f71c9c5103a607bb34db9a8063edb8e6ffe25e2d4f00a72ccad1cda54d706da4cb6

test:
  secret_key_base: 9d6b14a076a7e7369ee70a69278e238cd129b986316232e67925dc4d30b99667744aedee33cdab754644f4c80859b5b69de64d707d67b6dd912911a6bf805d0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
